#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["AplicacionWeb1/AplicacionWeb1.csproj", "AplicacionWeb1/"]
RUN dotnet restore "./AplicacionWeb1/./AplicacionWeb1.csproj"
COPY . .
WORKDIR "/src/AplicacionWeb1"
RUN dotnet build "/AplicacionWeb1.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./AplicacionWeb1.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

COPY AplicacionWeb1/wwwroot/css /app/wwwroot/css
COPY AplicacionWeb1/wwwroot/images /app/wwwroot/Img

ENTRYPOINT ["dotnet", "AplicacionWeb1.dll"]